services:
  - type: web
    name: registra-mente
    env: python
    buildCommand: apt-get update -y && apt-get install -y portaudio19-dev && pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
