services:
  - type: web
    name: registra-mente
    env: python
    buildCommand: bash ./build.sh
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
